apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pq93s0gau-python
  janus-idp.io/tekton: pq93s0gau-python
  backstage.io/kubernetes-id: pq93s0gau-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pq93s0gau-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
